title: Digitaler Produktpass
subtitle: Bargeld anstatt Werkstattbesuch! In unter 5 Minuten zum Kostenvoranschlag! Mit MrFiktiv schnell und einfach Fahrzeugschäden abrechnen.
baseurl: /
permalink: "/:year/:month/:day/:title/"
# Google Analytics
google_analytics: UA-178049998-1
collections:
  posts:
    permalink: "/blog/:year/:month/:day/:title/"

header:
  title: Digitaler Produktpass
  logo_img: images/scan.png
  has_nav: true
  nav:
    Produkt: "index"  
  palette: blue
  menu:
    actions:
      - label: Sign Up
        url: /signup
footer:
  logo_img: images/scan.png
  tagline: Der digitale Produktpass
  content: 
  links:
    - text: Datenschutz
      url: "/datenschutz"
      new_window: false

  nav_title: Company
  nav:
    Produkt: "index"

defaults:
  -
    scope:
      path:            "drafts/**"
    values:
      sitemap:         false
  -
    scope:
      path:            "images/**"
    values:
      sitemap:         false

sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
